# Generated by Django 4.1.1 on 2022-11-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.BigIntegerField(default=1),
        ),
    ]
