# Generated by Django 4.1.1 on 2022-11-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.BigIntegerField(),
        ),
    ]
