# Generated by Django 4.0.6 on 2022-10-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_firstname', models.CharField(max_length=20)),
                ('s_secondname', models.CharField(max_length=20)),
                ('s_email', models.CharField(max_length=70)),
                ('s_number', models.BigIntegerField()),
                ('s_address', models.CharField(max_length=100)),
                ('s_accountnumber', models.BigIntegerField()),
                ('s_ifsc', models.CharField(max_length=20)),
                ('s_accholder', models.CharField(max_length=40)),
                ('s_password', models.CharField(max_length=8)),
                ('s_image', models.ImageField(upload_to='seller/')),
            ],
        ),
    ]
