# Generated by Django 4.1.1 on 2022-11-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
